const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Touch,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Particles,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.destroy,
		C3.Behaviors.Persist,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Behaviors.LOS,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Particles.Acts.SetParticleObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Particles.Acts.SetInitOpacity,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetYRandomiser,
		C3.Plugins.Particles.Acts.SetSprayCone,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Exps.MaxFallSpeed,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.Touch.Exps.AbsoluteXForID,
		C3.Plugins.Touch.Exps.AbsoluteYForID,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Exps.Deceleration,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.IsFlipped,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.RestoreObjectTimescale,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetDefaultColor
	];
};
self.C3_JsPropNameTable = [
	{Jump: 0},
	{Prebuff: 0},
	{Abilty: 0},
	{WithItem: 0},
	{UIDToTrhow: 0},
	{Thowing: 0},
	{isHurted: 0},
	{hp: 0},
	{isDead: 0},
	{desacelationOriginal: 0},
	{Platform: 0},
	{Tween: 0},
	{Timer: 0},
	{Flash: 0},
	{Player: 0},
	{Keyboard: 0},
	{ThrowDetector: 0},
	{Gamepad: 0},
	{Touch: 0},
	{Solid: 0},
	{Tilemap: 0},
	{originalPos: 0},
	{bg: 0},
	{bg2: 0},
	{bg3: 0},
	{bg4: 0},
	{bg5: 0},
	{bg6: 0},
	{portrait: 0},
	{Anchor: 0},
	{Dialogo: 0},
	{DialogueText: 0},
	{Dialogue: 0},
	{Portrait: 0},
	{DialogoTrigger: 0},
	{DialogoTriggerExit: 0},
	{ID: 0},
	{bg_holo: 0},
	{Dpad_rigth: 0},
	{key_right: 0},
	{holo_walk: 0},
	{Browser: 0},
	{grandma: 0},
	{RunParticles: 0},
	{ScrollTo: 0},
	{MoveTo: 0},
	{Cam: 0},
	{Taken: 0},
	{AcelerationOnFloor: 0},
	{Peso: 0},
	{ActualBounciness: 0},
	{DistanceThwon: 0},
	{PosX: 0},
	{PosY: 0},
	{Take: 0},
	{Key: 0},
	{rock: 0},
	{Bullet: 0},
	{Boomerang: 0},
	{Dado: 0},
	{box: 0},
	{Apple: 0},
	{Text: 0},
	{Diamond: 0},
	{Coins: 0},
	{CoinParticles: 0},
	{hitEffect: 0},
	{DiamaondParticlesHit: 0},
	{DiamaondParticles: 0},
	{Door: 0},
	{Mask: 0},
	{Audio: 0},
	{DiamondGUI: 0},
	{CoinsGUI: 0},
	{monedaCount: 0},
	{Heart: 0},
	{NeedReposition: 0},
	{originalX: 0},
	{Touch_Button: 0},
	{GameLevelInfo: 0},
	{GamePad_ActionDoor: 0},
	{DoorInteractionZ: 0},
	{Touch_Jump: 0},
	{Jumpthru: 0},
	{Stake: 0},
	{StakeCollision: 0},
	{Castillo: 0},
	{Laboratorio: 0},
	{Playa: 0},
	{Bosque: 0},
	{CuevaDeFuego: 0},
	{CuevaDeHielo: 0},
	{Caverna: 0},
	{Sprite: 0},
	{Cave: 0},
	{BGTouch: 0},
	{enemyHP: 0},
	{mov: 0},
	{Slime: 0},
	{waypoint: 0},
	{EnemyDed: 0},
	{Sine: 0},
	{Bat: 0},
	{Espina: 0},
	{BloqueEspina: 0},
	{Titile: 0},
	{PlatformInfo: 0},
	{PressAnyButton: 0},
	{n: 0},
	{n2: 0},
	{BlackTransition: 0},
	{Cursor: 0},
	{Abejja: 0},
	{DestroyOutsideLayout: 0},
	{Saeta: 0},
	{SlimeSpinoso: 0},
	{heighJump: 0},
	{speed: 0},
	{Flama: 0},
	{Mole: 0},
	{Persist: 0},
	{Respawn: 0},
	{id: 0},
	{CheckPoin: 0},
	{WindZone: 0},
	{WindParticles: 0},
	{FloorDetector: 0},
	{Logo_Ulpomedia: 0},
	{Cost: 0},
	{RunParticleSelector: 0},
	{RunParticleObject_: 0},
	{ParticleCost: 0},
	{ParticlesData: 0},
	{LocalStorage: 0},
	{level: 0},
	{Unlock: 0},
	{LevelSelector: 0},
	{OverMap: 0},
	{SelectorLevel: 0},
	{bgSelectLevel: 0},
	{n3: 0},
	{LevelSelectionNumber: 0},
	{LevelName: 0},
	{unknown: 0},
	{Sprite2: 0},
	{Screen: 0},
	{TextOver: 0},
	{MenuSelector2: 0},
	{MenuTextButton: 0},
	{canClick: 0},
	{MenuObject: 0},
	{MenuOptionsOver: 0},
	{OptionPanel: 0},
	{Mute: 0},
	{ButtonVolume: 0},
	{DiamondGUI2: 0},
	{Mouse: 0},
	{state: 0},
	{LineOfSight: 0},
	{Penguin: 0},
	{Robot: 0},
	{Doggo: 0},
	{AdReward: 0},
	{NextWorld: 0},
	{BG_large: 0},
	{BG_short: 0},
	{OptionText: 0},
	{ShopGo: 0},
	{DeleteButton: 0},
	{LevelSelectorGo: 0},
	{RetryButton: 0},
	{GoToMenu: 0},
	{CreditBurrton: 0},
	{Relics: 0},
	{RelicParticle: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Ligth: 0},
	{Ligth2: 0},
	{Particles6: 0},
	{box2: 0},
	{Ligthbox: 0},
	{CloseOptionReal: 0},
	{DeleteText: 0},
	{CreditsTxt: 0},
	{CloseOptionReal2: 0},
	{"100Coins": 0},
	{Hojas: 0},
	{Particles7: 0},
	{IsObjectPreview: 0},
	{PreviewGame: 0},
	{RunParticleObject_2: 0},
	{Coins2: 0},
	{CoinsOnLevel: 0},
	{Sprite3: 0},
	{PopUpINFO: 0},
	{OptionPanel2: 0},
	{No: 0},
	{Yes: 0},
	{CostParticle: 0},
	{No2: 0},
	{Yes2: 0},
	{CloseCredits: 0},
	{Black: 0},
	{AdReward2: 0},
	{Sprite4: 0},
	{Black2: 0},
	{Touch_Button2: 0},
	{bgCastle: 0},
	{sanaPad: 0},
	{XP: 0},
	{YP: 0},
	{conAngle: 0},
	{sanaStick: 0},
	{GamePadButton: 0},
	{marco: 0},
	{display: 0},
	{cost: 0},
	{Showing: 0},
	{PlayerSelect: 0},
	{Sprite5: 0},
	{SkinCost: 0},
	{skinInfo: 0},
	{CostParticleSkin: 0},
	{NoSkin: 0},
	{YesSkin: 0},
	{diamondMenu: 0},
	{SkipLevel: 0},
	{Sprite6: 0},
	{Touch_Action: 0},
	{Platform2: 0},
	{ObjectToThrow: 0},
	{Enemy: 0},
	{TileMaps: 0},
	{GUI: 0},
	{GUITEXT: 0},
	{jumping: 0},
	{OriginalFallSpeed: 0},
	{deadZone: 0},
	{coyoteTime: 0},
	{prebuffTime: 0},
	{Mobile: 0},
	{FallingMultiplier: 0},
	{direction: 0},
	{EnemyPos: 0},
	{isHurtFromFall: 0},
	{touchID: 0},
	{dist: 0},
	{cangle: 0},
	{radius: 0},
	{X: 0},
	{Y: 0},
	{ShowY: 0},
	{HideY: 0},
	{SpeedText: 0},
	{levelCoin: 0},
	{AdFasterComplete: 0},
	{place: 0},
	{NeedAdLevel: 0},
	{Pressing: 0},
	{CoinCount: 0},
	{In: 0},
	{SpeedShot: 0},
	{startGame: 0},
	{actualLevel: 0},
	{actualParticle: 0},
	{volumeAudio: 0},
	{tempID: 0},
	{tempCost: 0},
	{totalLevelComplete: 0},
	{totalLevels: 0},
	{firstTime: 0},
	{danaSkin: 0},
	{selectable: 0},
	{actualWorld: 0},
	{firstAd: 0},
	{FromLevelOrMenu: 0},
	{storyTime: 0},
	{dialogue_number: 0},
	{StoryTime_local: 0},
	{FromLevel: 0},
	{show: 0},
	{diamondComplete: 0},
	{idElement: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	ThrowDetector: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	bg: class extends self.ISpriteInstance {},
	bg2: class extends self.ISpriteInstance {},
	bg3: class extends self.ISpriteInstance {},
	bg4: class extends self.ISpriteInstance {},
	bg5: class extends self.ISpriteInstance {},
	bg6: class extends self.ISpriteInstance {},
	portrait: class extends self.ISpriteInstance {},
	Dialogo: class extends self.ISpriteInstance {},
	DialogueText: class extends self.ITextInstance {},
	DialogoTrigger: class extends self.ISpriteInstance {},
	DialogoTriggerExit: class extends self.ISpriteInstance {},
	bg_holo: class extends self.ISpriteInstance {},
	Dpad_rigth: class extends self.ISpriteInstance {},
	key_right: class extends self.ISpriteInstance {},
	holo_walk: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	grandma: class extends self.ISpriteInstance {},
	RunParticles: class extends self.IParticlesInstance {},
	Cam: class extends self.ISpriteInstance {},
	Key: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	Boomerang: class extends self.ISpriteInstance {},
	Dado: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	Apple: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Diamond: class extends self.ISpriteInstance {},
	Coins: class extends self.ISpriteInstance {},
	CoinParticles: class extends self.IParticlesInstance {},
	hitEffect: class extends self.ISpriteInstance {},
	DiamaondParticlesHit: class extends self.IParticlesInstance {},
	DiamaondParticles: class extends self.IParticlesInstance {},
	Door: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	DiamondGUI: class extends self.ISpriteInstance {},
	CoinsGUI: class extends self.ISpriteInstance {},
	monedaCount: class extends self.ITextInstance {},
	Heart: class extends self.ISpriteInstance {},
	Touch_Button: class extends self.ISpriteInstance {},
	GameLevelInfo: class extends self.IArrayInstance {},
	GamePad_ActionDoor: class extends self.ISpriteInstance {},
	DoorInteractionZ: class extends self.ISpriteInstance {},
	Touch_Jump: class extends self.ISpriteInstance {},
	Stake: class extends self.ISpriteInstance {},
	StakeCollision: class extends self.ISpriteInstance {},
	Castillo: class extends self.ITilemapInstance {},
	Laboratorio: class extends self.ITilemapInstance {},
	Playa: class extends self.ITilemapInstance {},
	Bosque: class extends self.ITilemapInstance {},
	CuevaDeFuego: class extends self.ITilemapInstance {},
	CuevaDeHielo: class extends self.ITilemapInstance {},
	Caverna: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Cave: class extends self.ISpriteInstance {},
	BGTouch: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	waypoint: class extends self.ISpriteInstance {},
	EnemyDed: class extends self.IParticlesInstance {},
	Bat: class extends self.ISpriteInstance {},
	Espina: class extends self.ISpriteInstance {},
	BloqueEspina: class extends self.ISpriteInstance {},
	Titile: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	PressAnyButton: class extends self.ITextInstance {},
	n: class extends self.ISpriteInstance {},
	n2: class extends self.ISpriteInstance {},
	BlackTransition: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Abejja: class extends self.ISpriteInstance {},
	Saeta: class extends self.ISpriteInstance {},
	SlimeSpinoso: class extends self.ISpriteInstance {},
	Flama: class extends self.ISpriteInstance {},
	Mole: class extends self.ISpriteInstance {},
	Respawn: class extends self.ISpriteInstance {},
	CheckPoin: class extends self.ISpriteInstance {},
	WindZone: class extends self.ISpriteInstance {},
	WindParticles: class extends self.IParticlesInstance {},
	FloorDetector: class extends self.ISpriteInstance {},
	Logo_Ulpomedia: class extends self.ISpriteInstance {},
	RunParticleSelector: class extends self.ISpriteInstance {},
	RunParticleObject_: class extends self.ISpriteInstance {},
	ParticleCost: class extends self.ITextInstance {},
	ParticlesData: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	LevelSelector: class extends self.ISpriteInstance {},
	OverMap: class extends self.ISpriteInstance {},
	SelectorLevel: class extends self.ISpriteInstance {},
	bgSelectLevel: class extends self.ISpriteInstance {},
	n3: class extends self.ISpriteInstance {},
	LevelSelectionNumber: class extends self.ITextInstance {},
	LevelName: class extends self.ITextInstance {},
	unknown: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MenuSelector2: class extends self.ISpriteInstance {},
	MenuTextButton: class extends self.ITextInstance {},
	MenuObject: class extends self.ISpriteInstance {},
	MenuOptionsOver: class extends self.ISpriteInstance {},
	OptionPanel: class extends self.ISpriteInstance {},
	ButtonVolume: class extends self.ISpriteInstance {},
	DiamondGUI2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Penguin: class extends self.ISpriteInstance {},
	Robot: class extends self.ISpriteInstance {},
	Doggo: class extends self.ISpriteInstance {},
	AdReward: class extends self.ISpriteInstance {},
	NextWorld: class extends self.ISpriteInstance {},
	BG_large: class extends self.ISpriteInstance {},
	BG_short: class extends self.ISpriteInstance {},
	OptionText: class extends self.ITextInstance {},
	ShopGo: class extends self.ISpriteInstance {},
	DeleteButton: class extends self.ISpriteInstance {},
	LevelSelectorGo: class extends self.ISpriteInstance {},
	RetryButton: class extends self.ISpriteInstance {},
	GoToMenu: class extends self.ISpriteInstance {},
	CreditBurrton: class extends self.ISpriteInstance {},
	Relics: class extends self.ISpriteInstance {},
	RelicParticle: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Ligth: class extends self.ISpriteInstance {},
	Ligth2: class extends self.ISpriteInstance {},
	Particles6: class extends self.IParticlesInstance {},
	box2: class extends self.ISpriteInstance {},
	Ligthbox: class extends self.ISpriteInstance {},
	CloseOptionReal: class extends self.ISpriteInstance {},
	DeleteText: class extends self.ITextInstance {},
	CreditsTxt: class extends self.ITextInstance {},
	CloseOptionReal2: class extends self.ISpriteInstance {},
	_100Coins: class extends self.ITextInstance {},
	Hojas: class extends self.ISpriteInstance {},
	Particles7: class extends self.IParticlesInstance {},
	RunParticleObject_2: class extends self.ISpriteInstance {},
	Coins2: class extends self.ISpriteInstance {},
	CoinsOnLevel: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	PopUpINFO: class extends self.ITextInstance {},
	OptionPanel2: class extends self.ISpriteInstance {},
	No: class extends self.ISpriteInstance {},
	Yes: class extends self.ISpriteInstance {},
	CostParticle: class extends self.ITextInstance {},
	No2: class extends self.ISpriteInstance {},
	Yes2: class extends self.ISpriteInstance {},
	CloseCredits: class extends self.ISpriteInstance {},
	Black: class extends self.ISpriteInstance {},
	AdReward2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Black2: class extends self.ISpriteInstance {},
	Touch_Button2: class extends self.ISpriteInstance {},
	bgCastle: class extends self.ISpriteInstance {},
	sanaPad: class extends self.ISpriteInstance {},
	sanaStick: class extends self.ISpriteInstance {},
	GamePadButton: class extends self.ISpriteInstance {},
	marco: class extends self.ISpriteInstance {},
	PlayerSelect: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	SkinCost: class extends self.ITextInstance {},
	skinInfo: class extends self.IArrayInstance {},
	CostParticleSkin: class extends self.ITextInstance {},
	NoSkin: class extends self.ISpriteInstance {},
	YesSkin: class extends self.ISpriteInstance {},
	diamondMenu: class extends self.ISpriteInstance {},
	SkipLevel: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Touch_Action: class extends self.ISpriteInstance {},
	ObjectToThrow: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	TileMaps: class extends self.ITilemapInstance {},
	GUI: class extends self.ISpriteInstance {},
	GUITEXT: class extends self.ITextInstance {}
}